---
title: "Dynamic Prediction PLM"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
# graphics.off()
# rm(list = ls())
# freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(lme4, quietly = TRUE)
library(devtools, quietly = TRUE)
library(optimx, quietly = TRUE)

devtools::load_all()
## check the directory for the file
# here::dr_here()
# here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```

## Function `meanout()`

```{r}
meanout <- function(dataset,
                    term = c("bias", "mse", "coverage50",
                             "coverage80", "coverage90"),
                    ...){
  result <- dataset$centiles_observed %>%
    mutate(mse = bias^2) %>%
    dplyr::select(bias, mse, coverage50, coverage80, coverage90) %>%
    colMeans(na.rm = TRUE)
  
  return(result)
}
```


## Without weights

```{r}
#| include: false
#| eval: false
load("~/Desktop/plmphd/R/train_test.rda")
plt1_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 1) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = 0.95,
                 # match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt1_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 2) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 2, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt3_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 3) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 3, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt4_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 4) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 4, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt1_4anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 1) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(3, 6, 9, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt1_4anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 2) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 2, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(3, 6, 9, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt3_4anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 3) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 3, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(3, 6, 9, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt4_4anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 4) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 4, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(3, 6, 9, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt5_4anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 5) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 5, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(3, 6, 9, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

plt5_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 5) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 5, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

save(plt1_3anchor, plt1_3anchor, plt3_3anchor, plt4_3anchor, plt5_3anchor,
     plt1_4anchor, plt1_4anchor, plt3_4anchor, plt4_4anchor, plt5_4anchor,
     file = here::here("data", "plt12345_3anchor_4anchor.rda"))
```


```{r}
load("data/plt12345_3anchor_4anchor.rda")

summary_seed13 <- map_dfr(plt1_3anchor, ~try(meanout(.,)))
summary_seed23 <- map_dfr(plt1_3anchor, ~try(meanout(.,)))
summary_seed33 <- map_dfr(plt3_3anchor, ~try(meanout(.,)))
summary_seed43 <- map_dfr(plt4_3anchor, ~try(meanout(.,)))
summary_seed53 <- map_dfr(plt5_3anchor, ~try(meanout(.,)))

summary_seed14 <- map_dfr(plt1_4anchor, ~try(meanout(.,)))
summary_seed24 <- map_dfr(plt1_4anchor, ~try(meanout(.,)))
summary_seed34 <- map_dfr(plt3_4anchor, ~try(meanout(.,)))
summary_seed44 <- map_dfr(plt4_4anchor, ~try(meanout(.,)))
summary_seed54 <- map_dfr(plt5_4anchor, ~try(meanout(.,)))

dyn_results <- rbind(
      summary_seed13 %>% mutate(rmse = sqrt(mse)) %>% colMeans(),
      summary_seed23 %>% mutate(rmse = sqrt(mse)) %>% colMeans(),
      summary_seed33 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed43 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed53 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed14 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed24 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed34 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed44 %>% mutate(rmse = sqrt(mse)) %>%colMeans(),
      summary_seed54 %>% mutate(rmse = sqrt(mse)) %>%colMeans()) %>% 
  as.data.frame() %>% 
  dplyr::select(bias, rmse, coverage50, coverage80, coverage90)


library(xtable)
xtable(dyn_results, type = "latex", digits = 4)

print(xtable(dyn_results, type = "latex"),
      file = paste0("figures/S12_dyn_plt12345_anchor34_summary.tex"))
```



<!-- ## With weights -->

<!-- ```{r} -->
<!-- wplt1_3anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 1) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 1, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(4, 8, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->
<!-- wplt1_3anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 2) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 2, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(4, 8, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->
<!-- wplt3_3anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 3) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 3, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(4, 8, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt4_3anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 4) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 4, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(4, 8, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt1_4anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 1) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 1, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(3, 6, 9, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt1_4anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 2) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 2, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(3, 6, 9, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt3_4anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 3) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 3, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(3, 6, 9, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->
<!-- wplt4_4anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 4) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 4, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(3, 6, 9, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt5_4anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 5) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 5, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(3, 6, 9, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- wplt5_3anchor <- people_like_wee(train_data = train, -->
<!--                  test_data = test, -->
<!--                  new_data = test %>% filter(time <= 5) %>% group_by(id), -->
<!--                  outcome_var = "ht", -->
<!--                  time_var = "time", -->
<!--                  id_var = "id", -->
<!--                  tmin = 5, tmax = 20, -->
<!--                  bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)", -->
<!--                  anchor_time = c(4, 8, 12), -->
<!--                  gamlss_formula = "ht ~ cs(time, df = 3)", -->
<!--                  gamlss_sigma = "~ cs(time, df = 1)", -->
<!--                  match_methods = "mahalanobis", -->
<!--                  weight = TRUE, -->
<!--                  match_alpha = 0, -->
<!--                  match_plot = FALSE, -->
<!--                  predict_plot = FALSE) -->

<!-- save(wplt1_3anchor, wplt1_3anchor, wplt3_3anchor, wplt4_3anchor, wplt5_3anchor, -->
<!--      wplt1_4anchor, wplt1_4anchor, wplt3_4anchor, wplt4_4anchor, wplt5_4anchor, -->
<!--      file = here::here("data", "wplt12345_3anchor_4anchor.rda")) -->
<!-- ``` -->

<!-- ### With weights Summary -->

<!-- ```{r} -->
<!-- load("data/wplt12345_3anchor_4anchor.rda") -->

<!-- summary_seed13 <- map_dfr(wplt1_3anchor, ~try(meanout(.,))) -->
<!-- summary_seed23 <- map_dfr(wplt1_3anchor, ~try(meanout(.,))) -->
<!-- summary_seed33 <- map_dfr(wplt3_3anchor, ~try(meanout(.,))) -->
<!-- summary_seed43 <- map_dfr(wplt4_3anchor, ~try(meanout(.,))) -->
<!-- summary_seed53 <- map_dfr(wplt5_3anchor, ~try(meanout(.,))) -->

<!-- summary_seed14 <- map_dfr(wplt1_4anchor, ~try(meanout(.,))) -->
<!-- summary_seed24 <- map_dfr(wplt1_4anchor, ~try(meanout(.,))) -->
<!-- summary_seed34 <- map_dfr(wplt3_4anchor, ~try(meanout(.,))) -->
<!-- summary_seed44 <- map_dfr(wplt4_4anchor, ~try(meanout(.,))) -->
<!-- summary_seed54 <- map_dfr(wplt5_4anchor, ~try(meanout(.,))) -->

<!-- dyn_results <- rbind( -->
<!--       summary_seed13 %>% mutate(rmse = sqrt(mse)) %>% colMeans(), -->
<!--       summary_seed23 %>% mutate(rmse = sqrt(mse)) %>% colMeans(), -->
<!--       summary_seed33 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed43 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed53 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed14 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed24 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed34 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed44 %>% mutate(rmse = sqrt(mse)) %>%colMeans(), -->
<!--       summary_seed54 %>% mutate(rmse = sqrt(mse)) %>%colMeans()) %>%  -->
<!--   as.data.frame() %>%  -->
<!--   dplyr::select(bias, rmse, coverage50, coverage80, coverage90) -->


<!-- library(xtable) -->
<!-- xtable(dyn_results, type = "latex", digits = 4) -->

<!-- print(xtable(dyn_results, type = "latex"), -->
<!--       file = paste0("figures/S13_dyn_wplt12345_anchor34_summary.tex")) -->
<!-- ``` -->


## Simulation study

```{r}
#| include: false
#| eval: false

for (i in 100:51){
  set.seed(i)
  ## simulate data -------------------------------------------------------------
  Nid <- rpois(20000, 20)
  Ntime <- map(Nid, ~rnorm(.x, 0.8, 0.3) %>%
                 abs() %>%
                 as.data.frame())
  
  data0 <- cbind(id = 1:20000,
                 group = rep(c("training", "testing"), by = 10000),
                 gap = Ntime,
                 sex = rep(c("M", "F"), each = 10000)) %>%
    as.data.frame() %>%
    mutate(hmax = c(rnorm(10000, 175, 10),
                    rnorm(10000, 160, 11)),
           hd = c(rnorm(10000, 20, 4),
                  rnorm(10000, 20, 6.5)),
           rate = runif(20000, 5.8, 11),
           s1 = c(abs(rnorm(10000, 0.85, 0.1)),
                  abs(rnorm(10000, 0.75, 0.1))),
           theta = c(runif(10000, 11, 17),
                     runif(10000, 10, 15))) %>%
    mutate(s0 = s1 / rate,
           h3 = hmax - 2 * hd / (exp(s0 *(3 - theta)) + exp(s1 * (3 - theta))),
           h10 = hmax - 2 * hd/ (exp(s0 *(10 - theta)) + exp(s1 * (10 - theta))),
           h20 = hmax - 2 * hd / (exp(s0 *(20 - theta)) + exp(s1 * (20 - theta))),
           sex = unlist(sex),
           group = unlist(group),
           id = as.character(unlist(id))) %>%
    filter(h3 > 80,
           h3 < 106,
           hd > 15,
           h10 > 100) %>%
    group_by(group, sex) %>%
    slice_sample(n = 300L) %>%
    ungroup()
  
  simulation <- data0 %>%
    unnest(gap) %>%
    dplyr::select(gap = 3, everything()) %>%
    group_by(id) %>%
    mutate(time = lag(cumsum(gap), default = 0) + 3) %>%
    ungroup() %>%
    filter(time <= 20) %>%
    mutate(resid = rnorm(n(), 0, 1),
           ht = hmax - 2 * hd /
             (exp(s0 *(time - theta)) + exp(s1 * (time - theta))) + resid) %>%
    as.data.frame() %>%
    mutate(time1 = as.numeric(time)) %>%
    mutate(time = round(time1, 1)) %>%
    dplyr::select(ht, id, sex, time, group)
  
  train <- dplyr::filter(simulation, group == "training")
  test <- dplyr::filter(simulation, group == "testing")
  test_base <- test %>%  group_by(id) %>% slice(1L) %>% ungroup()
  id_test <- unique(test$id)
  
  plt0_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test_base,
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 2, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

  save(plt0_3anchor, file = here::here("data", paste0("plt0_3anchor_", i, ".rda")))
  
    plt1_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 3 + 1) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 2, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)

  save(plt1_3anchor, file = here::here("data", paste0("plt1_3anchor_", i, ".rda")))
  
  plt2_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 3 + 2) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)
  save(plt2_3anchor, file = here::here("data", paste0("plt2_3anchor_", i, ".rda")))
  
    plt3_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 3 + 3) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)
  save(plt3_3anchor, file = here::here("data", paste0("plt3_3anchor_", i, ".rda")))
  
      plt4_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 4 + 3) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)
  save(plt4_3anchor, file = here::here("data", paste0("plt4_3anchor_", i, ".rda")))
  
  plt5_3anchor <- people_like_thee(train_data = train,
                 test_data = test,
                 new_data = test %>% filter(time <= 5 + 3) %>% group_by(id),
                 outcome_var = "ht",
                 time_var = "time",
                 id_var = "id",
                 tmin = 1, tmax = 20,
                 bks_fixed = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 bks_random = "1 + bs(time, knots = c(5, 10, 15), degree = 1)",
                 anchor_time = c(4, 8, 12),
                 gamlss_formula = "ht ~ cs(time, df = 3)",
                 gamlss_sigma = "~ cs(time, df = 1)",
                 match_methods = "mahalanobis",
                 weight = FALSE,
                 match_alpha = NULL,
                 match_number = 30,
                 match_plot = FALSE,
                 predict_plot = FALSE)
  save(plt5_3anchor, file = here::here("data", paste0("plt5_3anchor_", i, ".rda")))
}
```

