---
title: "Simulation"
date: "2025-01-16"
---

```{r message=FALSE, warning=FALSE}
# Load necessary library
library(lme4, quietly = TRUE)
library(devtools, quietly = TRUE)
library(tidyverse, quietly = TRUE)
load_all()
```

## Sin Simulation Pullout

```{r eval=FALSE, include=FALSE}
sin_simulation <- function(file_location, file){
  load(paste0(file_location, file))
  Ma080 <- Ma080 %>%
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Ma080") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  Ma090 <- Ma090 %>%
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Ma090") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  Ma095 <- Ma095 %>%
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Ma095") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  Mn20 <- Mn20 %>%
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Mn20") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  Mn25 <- Mn25 %>%
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Mn25") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  Mn30 <- Mn30 %>% 
    mutate(time = c(0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5),
           anchor = rep(c(3, 4), each = 6),
           methods = "Mn30") %>%
    dplyr::select(methods, anchor, time, bias, rmse, 
           coverage50, coverage80, coverage90)
  
  results <- bind_rows(Ma080 = Ma080,
                       Ma090 = Ma090,
                       Ma095 = Ma095,
                       Mn20 = Mn20,
                       Mn25 = Mn25,
                       Mn30 = Mn30)
}

folder1 <- "results"
folder2 <- "dyn_results_gender"
# folder2 <- "constant_var"

file_location <- paste0(folder1, "/", folder2, "/")
files <- list.files(path = file_location, pattern = ".Rdata")

## pull out the simulation results from the folder each as a list of
## bias, rmse, coverage50, coverage80, and coverage90
sim_ss <- map(files, ~sin_simulation(file_location, .),
                     .progress = list(type = "iterator",
                                      format = "Calculating {cli::pb_bar} {cli::pb_percent}",
                                      clear = TRUE)) %>% bind_rows() 
final_names <- sim_ss %>% 
  group_by(methods, anchor, time) %>% 
  summarize(n = n()) 

final_ss1 <- sim_ss %>% 
  group_by(methods, anchor, time) %>% 
  group_map(~colMeans(.x, na.rm = TRUE) %>% 
              as.data.frame()) %>%
  bind_cols() %>%
  t() %>%
  as.data.frame() %>%
  cbind(final_names) %>%
  filter(anchor == 4) %>% 
  dplyr::select(-n) %>%
  dplyr::select(anchor, methods, time, everything()) %>%
  mutate(anchor = "t(4, 8, 12, 16)",
         time = rep(c("baseline", "1 year", "2 year", "3 year", "4 year", "5 year"), 6))

library(xtable)
xtable(final_ss1)
print(xtable(final_ss1), file = "tables/T13_4anchor_481216_simulation_with_gender.tex")
```


rsync -a goodgolden_555\@ap21.uc.osg-htc.org:/home/goodgolden_555/dyn_results results
